version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - health

  nats-1:
    image: nats:alpine
    volumes:
      - ./nats/nats-server-1.conf:/etc/nats/nats-server.conf
      - .tmp/nats/data/jetstream/1:/data/jetstream
    ports:
      - "4223:4222"
      - "8223:8222"
    networks:
      - health

  nats-2:
    image: nats:alpine
    volumes:
      - ./nats/nats-server-2.conf:/etc/nats/nats-server.conf
      - .tmp/nats/data/jetstream/2:/data/jetstream
    ports:
      - "4224:4222"
      - "8224:8222"
    networks:
      - health

  database:
    image: postgres:15.0-alpine
    volumes:
      - .tmp/postgres/data/:/data/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=doutorequemtemdoutorado 
      - POSTGRES_DB=health
      - PGDATA=/data/postgres
    networks:
      - health


  health-api:
    build:
        context: ./health-api
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - BMR_SERVICE_ENDPOINT=bmr-grpc:30000
      - IMC_SERVICE_ENDPOINT=imc-grpc:30000
      - RECOMMENDATIONS_SERVICE_ENDPOINT=recommendations-grpc:30000
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
      - NATS_URI=nats://nats-1:4222,nats://nats-2:4222
    ports:
        - 8080:8080
    volumes:
        - ./health-api:/go/src/health-api
    networks:
      - health
    depends_on:
      - nats-1
      - nats-2

  bmr-grpc:
    build:
        context: ./bmr-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30000:30000
    volumes:
        - ./bmr-grpc-service:/go/src/bmr-grpc-service
    networks:
      - health
  imc-grpc:
    build:
        context: ./imc-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30001:30000
    volumes:
        - ./imc-grpc-service:/go/src/imc-grpc-service
    networks:
      - health
      
  recommendations-grpc:
    build:
        context: ./recommendations-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - PROTEINS_SERVICE_ENDPOINT=proteins-grpc:30000
      - WATER_SERVICE_ENDPOINT=water-grpc:30000
      - CALORIES_SERVICE_ENDPOINT=calories-grpc:30000
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30002:30000
    volumes:
        - ./recommendations-grpc-service:/go/src/recommendations-grpc-service
    networks:
      - health

  proteins-grpc:
    build:
        context: ./proteins-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30003:30000
    volumes:
        - ./proteins-grpc-service:/go/src/proteins-grpc-service
    networks:
      - health

  water-grpc:
    build:
        context: ./water-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30004:30000
    volumes:
        - ./water-grpc-service:/go/src/water-grpc-service
    networks:
      - health

  calories-grpc:
    build:
        context: ./calories-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30005:30000
    volumes:
        - ./calories-grpc-service:/go/src/calories-grpc-service
    networks:
      - health

  database-store-service:
    build:
        context: ./database-store-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
      - NATS_URI=nats://nats-1:4222,nats://nats-2:4222
      - DB_USER=pguser
      - DB_HOST=database
      - DB_PORT=5432
      - DB_PASSWORD=doutorequemtemdoutorado 
      - DB_SCHEMA=health
      - MIGRATIONS_PATH=./migrations
    volumes:
        - ./database-store-service:/go/src/database-store-service
    networks:
      - health
    depends_on:
      - health-api
      - nats-1
      - nats-2
      - database

networks:
  health: