version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - health
  health-api:
    build:
        context: ./health-api
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - BMR_SERVICE_ENDPOINT=bmr-grpc:30000
      - IMC_SERVICE_ENDPOINT=imc-grpc:30000
      - RECOMMENDATIONS_SERVICE_ENDPOINT=recommendations-grpc:30000
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 8080:8080
    volumes:
        - ./health-api:/go/src/health-api
    networks:
      - health
  bmr-grpc:
    build:
        context: ./bmr-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30000:30000
    volumes:
        - ./bmr-grpc-service:/go/src/bmr-grpc-service
    networks:
      - health
  imc-grpc:
    build:
        context: ./imc-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30001:30000
    volumes:
        - ./imc-grpc-service:/go/src/imc-grpc-service
    networks:
      - health
  recommendations-grpc:
    build:
        context: ./recommendations-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - PROTEINS_SERVICE_ENDPOINT=proteins-grpc:30000
      - WATER_SERVICE_ENDPOINT=water-grpc:30000
      - CALORIES_SERVICE_ENDPOINT=calories-grpc:30000
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30002:30000
    volumes:
        - ./recommendations-grpc-service:/go/src/recommendations-grpc-service
    networks:
      - health
  proteins-grpc:
    build:
        context: ./proteins-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30003:30000
    volumes:
        - ./proteins-grpc-service:/go/src/proteins-grpc-service
    networks:
      - health
  water-grpc:
    build:
        context: ./water-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30004:30000
    volumes:
        - ./water-grpc-service:/go/src/water-grpc-service
    networks:
      - health
  calories-grpc:
    build:
        context: ./calories-grpc-service
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
        - 30005:30000
    volumes:
        - ./calories-grpc-service:/go/src/calories-grpc-service
    networks:
      - health
networks:
  health: