name: 'bmr-grpc-service ci'
on:
  push:
  pull_request:
    types: [ opened, reopened ]
jobs:
  unit-test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: setup GOPATH into PATH
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true          

      - uses: actions/checkout@v2

      - name: Run's Golint
        working-directory: bmr-grpc-service
        run: |
            export PATH=$PATH:$(go env GOPATH)/bin
            go get -u golang.org/x/lint/golint
            # golint -set_exit_status ./...
            
      - name: Install dependencies
        working-directory: bmr-grpc-service
        run: go get -u 

      - name: Test
        working-directory: bmr-grpc-service
        run: go test -v

  build-docker-artifacts:
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17.x'

      - uses: actions/checkout@v1

      - name: Docker Build
        working-directory: bmr-grpc-service
        run: docker build -t bmr-grpc-service:latest .

      - name: Docker Tag Latest
        working-directory: bmr-grpc-service
        run: docker tag bmr-grpc-service:latest fidelissauro/bmr-grpc-service:latest

      - name: Docker Tag Release
        run: | 
          TAG=$(git describe --tags --abbrev=0)
          docker tag bmr-grpc-service:latest fidelissauro/bmr-grpc-service:$TAG
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Docker Push Latest
        working-directory: bmr-grpc-service
        run: docker push fidelissauro/bmr-grpc-service:latest

      - name: Docker Push Release Tag
        working-directory: bmr-grpc-service
        run: |
          TAG=$(git describe --tags --abbrev=0)
          docker push fidelissauro/bmr-grpc-service:$TAG
          